### ISSUE TITLE
Error adding new Facility

### ISSUE THREAD

**Issue by tom-karasch** [gaepdit/FMS#179] opened 2021-07-01 16:53 UTC
Error added new facility. Most likely linked to failure to assign new FileLabel before adding to Database.

**Comment by dougwaldron** [comment] 2021-07-06 18:57
Raygun report https://app.raygun.com/crashreporting/26p0xsd/errors/88621825764 has more details about the error

**Comment by dougwaldron** [comment] 2021-07-06 19:01
@tom-karasch I was investigating the linked crash report, and noticed it only occurs on the "Add" page, which you mentioned in the meeting today. I'm pretty sure this is the cause of your issue. I'll send the fix shortly.

**Comment by tom-karasch** [comment] 2021-07-06 19:26
Sam and I were tracing through this on Friday. It seems to fail while adding a new file label, thus not assigning a new file label to a new Facility. I have been working on the fix today. Send me a pull request, so I can see if my correction is close to yours. Thanks.

**Comment by dougwaldron** [comment] 2021-07-06 19:36
Okay, the bug I found happens well before the code to create a new File. I'll send the PR that fixes my bug and you can test if it fixes yours as well.

**Comment by dougwaldron** [comment] 2021-07-08 16:57
Fix has been deployed to DEV/UAT

**Closed as completed** 2021-07-23 21:43 UTC
Labels: bug
